;; DO NOT EDIT: File is generated by AWS-SDK/GENERATOR.

(common-lisp:defpackage #:aws-sdk/services/sdb/api
  (:use)
  (:nicknames #:aws/sdb)
  (:import-from #:aws-sdk/generator/shape)
  (:import-from #:aws-sdk/generator/operation)
  (:import-from #:aws-sdk/api)
  (:import-from #:aws-sdk/request)
  (:import-from #:aws-sdk/error))
(common-lisp:in-package #:aws-sdk/services/sdb/api)
(common-lisp:progn
 (common-lisp:defclass sdb-request (aws-sdk/request:request) common-lisp:nil
                       (:default-initargs :service "sdb" :protocol :query))
 (common-lisp:export 'sdb-request))
(common-lisp:progn
 (common-lisp:define-condition sdb-error
     (aws-sdk/error:aws-error)
     common-lisp:nil)
 (common-lisp:export 'sdb-error))
(common-lisp:defvar *error-map*
  '(("AttributeDoesNotExist" . attribute-does-not-exist)
    ("DuplicateItemName" . duplicate-item-name)
    ("InvalidNextToken" . invalid-next-token)
    ("InvalidNumberPredicates" . invalid-number-predicates)
    ("InvalidNumberValueTests" . invalid-number-value-tests)
    ("InvalidParameterValue" . invalid-parameter-value)
    ("InvalidQueryExpression" . invalid-query-expression)
    ("MissingParameter" . missing-parameter) ("NoSuchDomain" . no-such-domain)
    ("NumberDomainAttributesExceeded" . number-domain-attributes-exceeded)
    ("NumberDomainBytesExceeded" . number-domain-bytes-exceeded)
    ("NumberDomainsExceeded" . number-domains-exceeded)
    ("NumberItemAttributesExceeded" . number-item-attributes-exceeded)
    ("NumberSubmittedAttributesExceeded"
     . number-submitted-attributes-exceeded)
    ("NumberSubmittedItemsExceeded" . number-submitted-items-exceeded)
    ("RequestTimeout" . request-timeout)
    ("TooManyRequestedAttributes" . too-many-requested-attributes)))
(common-lisp:progn
 (common-lisp:defclass attribute common-lisp:nil
                       ((alternate-value-encoding :initarg
                         :alternate-value-encoding :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %attribute-alternate-value-encoding :initform
                         common-lisp:nil)
                        (value :initarg :value :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %attribute-value :initform
                         (common-lisp:error ":value is required"))
                        (alternate-name-encoding :initarg
                         :alternate-name-encoding :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %attribute-alternate-name-encoding :initform
                         common-lisp:nil)
                        (name :initarg :name :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %attribute-name :initform
                         (common-lisp:error ":name is required"))))
 (common-lisp:export (common-lisp:list 'attribute 'make-attribute))
 (common-lisp:defun make-attribute
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key alternate-value-encoding value
                     alternate-name-encoding name)
   (common-lisp:apply #'common-lisp:make-instance 'attribute
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        ((aws-sdk/generator/shape::input attribute))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        ((aws-sdk/generator/shape::input attribute))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'name))
      (common-lisp:list
       (common-lisp:cons "Name"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input
                           'alternate-name-encoding))
      (common-lisp:list
       (common-lisp:cons "AlternateNameEncoding"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'value))
      (common-lisp:list
       (common-lisp:cons "Value"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input
                           'alternate-value-encoding))
      (common-lisp:list
       (common-lisp:cons "AlternateValueEncoding"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        ((aws-sdk/generator/shape::input attribute))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:define-condition attribute-does-not-exist
     (sdb-error)
     ((box-usage :initarg :box-usage :initform common-lisp:nil :reader
       attribute-does-not-exist-box-usage)))
 (common-lisp:export
  (common-lisp:list 'attribute-does-not-exist
                    'attribute-does-not-exist-box-usage)))
(common-lisp:progn
 (common-lisp:deftype attribute-list () '(trivial-types:proper-list attribute))
 (common-lisp:defun |make-attribute-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list attribute))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:deftype attribute-name-list ()
   '(trivial-types:proper-list string))
 (common-lisp:defun |make-attribute-name-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list string))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:defclass batch-delete-attributes-request common-lisp:nil
                       ((items :initarg :items :type
                         (common-lisp:or deletable-item-list common-lisp:null)
                         :accessor %batch-delete-attributes-request-items
                         :initform (common-lisp:error ":items is required"))
                        (domain-name :initarg :domain-name :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %batch-delete-attributes-request-domain-name :initform
                         (common-lisp:error ":domain-name is required"))))
 (common-lisp:export
  (common-lisp:list 'batch-delete-attributes-request
                    'make-batch-delete-attributes-request))
 (common-lisp:defun make-batch-delete-attributes-request
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key items domain-name)
   (common-lisp:apply #'common-lisp:make-instance
                      'batch-delete-attributes-request
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        (
                         (aws-sdk/generator/shape::input
                          batch-delete-attributes-request))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        (
                         (aws-sdk/generator/shape::input
                          batch-delete-attributes-request))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'domain-name))
      (common-lisp:list
       (common-lisp:cons "DomainName"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'items))
      (common-lisp:list
       (common-lisp:cons "Items"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        (
                         (aws-sdk/generator/shape::input
                          batch-delete-attributes-request))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:defclass batch-put-attributes-request common-lisp:nil
                       ((items :initarg :items :type
                         (common-lisp:or replaceable-item-list
                                         common-lisp:null)
                         :accessor %batch-put-attributes-request-items
                         :initform (common-lisp:error ":items is required"))
                        (domain-name :initarg :domain-name :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %batch-put-attributes-request-domain-name :initform
                         (common-lisp:error ":domain-name is required"))))
 (common-lisp:export
  (common-lisp:list 'batch-put-attributes-request
                    'make-batch-put-attributes-request))
 (common-lisp:defun make-batch-put-attributes-request
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key items domain-name)
   (common-lisp:apply #'common-lisp:make-instance 'batch-put-attributes-request
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        (
                         (aws-sdk/generator/shape::input
                          batch-put-attributes-request))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        (
                         (aws-sdk/generator/shape::input
                          batch-put-attributes-request))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'domain-name))
      (common-lisp:list
       (common-lisp:cons "DomainName"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'items))
      (common-lisp:list
       (common-lisp:cons "Items"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        (
                         (aws-sdk/generator/shape::input
                          batch-put-attributes-request))
   common-lisp:nil))
(common-lisp:deftype boolean () 'common-lisp:boolean)
(common-lisp:progn
 (common-lisp:defclass create-domain-request common-lisp:nil
                       ((domain-name :initarg :domain-name :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %create-domain-request-domain-name :initform
                         (common-lisp:error ":domain-name is required"))))
 (common-lisp:export
  (common-lisp:list 'create-domain-request 'make-create-domain-request))
 (common-lisp:defun make-create-domain-request
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key domain-name)
   (common-lisp:apply #'common-lisp:make-instance 'create-domain-request
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        (
                         (aws-sdk/generator/shape::input
                          create-domain-request))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        (
                         (aws-sdk/generator/shape::input
                          create-domain-request))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'domain-name))
      (common-lisp:list
       (common-lisp:cons "DomainName"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        (
                         (aws-sdk/generator/shape::input
                          create-domain-request))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:defclass deletable-item common-lisp:nil
                       ((attributes :initarg :attributes :type
                         (common-lisp:or attribute-list common-lisp:null)
                         :accessor %deletable-item-attributes :initform
                         common-lisp:nil)
                        (name :initarg :name :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %deletable-item-name :initform
                         (common-lisp:error ":name is required"))))
 (common-lisp:export (common-lisp:list 'deletable-item 'make-deletable-item))
 (common-lisp:defun make-deletable-item
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key attributes name)
   (common-lisp:apply #'common-lisp:make-instance 'deletable-item
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        ((aws-sdk/generator/shape::input deletable-item))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        ((aws-sdk/generator/shape::input deletable-item))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'name))
      (common-lisp:list
       (common-lisp:cons "Name"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'attributes))
      (common-lisp:list
       (common-lisp:cons "Attributes"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        ((aws-sdk/generator/shape::input deletable-item))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:deftype deletable-item-list ()
   '(trivial-types:proper-list deletable-item))
 (common-lisp:defun |make-deletable-item-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list deletable-item))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:defclass delete-attributes-request common-lisp:nil
                       ((expected :initarg :expected :type
                         (common-lisp:or update-condition common-lisp:null)
                         :accessor %delete-attributes-request-expected
                         :initform common-lisp:nil)
                        (attributes :initarg :attributes :type
                         (common-lisp:or attribute-list common-lisp:null)
                         :accessor %delete-attributes-request-attributes
                         :initform common-lisp:nil)
                        (item-name :initarg :item-name :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %delete-attributes-request-item-name :initform
                         (common-lisp:error ":item-name is required"))
                        (domain-name :initarg :domain-name :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %delete-attributes-request-domain-name :initform
                         (common-lisp:error ":domain-name is required"))))
 (common-lisp:export
  (common-lisp:list 'delete-attributes-request
                    'make-delete-attributes-request))
 (common-lisp:defun make-delete-attributes-request
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key expected attributes item-name
                     domain-name)
   (common-lisp:apply #'common-lisp:make-instance 'delete-attributes-request
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        (
                         (aws-sdk/generator/shape::input
                          delete-attributes-request))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        (
                         (aws-sdk/generator/shape::input
                          delete-attributes-request))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'domain-name))
      (common-lisp:list
       (common-lisp:cons "DomainName"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'item-name))
      (common-lisp:list
       (common-lisp:cons "ItemName"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'attributes))
      (common-lisp:list
       (common-lisp:cons "Attributes"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'expected))
      (common-lisp:list
       (common-lisp:cons "Expected"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        (
                         (aws-sdk/generator/shape::input
                          delete-attributes-request))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:defclass delete-domain-request common-lisp:nil
                       ((domain-name :initarg :domain-name :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %delete-domain-request-domain-name :initform
                         (common-lisp:error ":domain-name is required"))))
 (common-lisp:export
  (common-lisp:list 'delete-domain-request 'make-delete-domain-request))
 (common-lisp:defun make-delete-domain-request
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key domain-name)
   (common-lisp:apply #'common-lisp:make-instance 'delete-domain-request
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        (
                         (aws-sdk/generator/shape::input
                          delete-domain-request))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        (
                         (aws-sdk/generator/shape::input
                          delete-domain-request))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'domain-name))
      (common-lisp:list
       (common-lisp:cons "DomainName"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        (
                         (aws-sdk/generator/shape::input
                          delete-domain-request))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:defclass domain-metadata-request common-lisp:nil
                       ((domain-name :initarg :domain-name :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %domain-metadata-request-domain-name :initform
                         (common-lisp:error ":domain-name is required"))))
 (common-lisp:export
  (common-lisp:list 'domain-metadata-request 'make-domain-metadata-request))
 (common-lisp:defun make-domain-metadata-request
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key domain-name)
   (common-lisp:apply #'common-lisp:make-instance 'domain-metadata-request
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        (
                         (aws-sdk/generator/shape::input
                          domain-metadata-request))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        (
                         (aws-sdk/generator/shape::input
                          domain-metadata-request))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'domain-name))
      (common-lisp:list
       (common-lisp:cons "DomainName"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        (
                         (aws-sdk/generator/shape::input
                          domain-metadata-request))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:defclass domain-metadata-result common-lisp:nil
                       ((timestamp :initarg :timestamp :type
                         (common-lisp:or integer common-lisp:null) :accessor
                         %domain-metadata-result-timestamp :initform
                         common-lisp:nil)
                        (attribute-values-size-bytes :initarg
                         :attribute-values-size-bytes :type
                         (common-lisp:or long common-lisp:null) :accessor
                         %domain-metadata-result-attribute-values-size-bytes
                         :initform common-lisp:nil)
                        (attribute-value-count :initarg :attribute-value-count
                         :type (common-lisp:or integer common-lisp:null)
                         :accessor
                         %domain-metadata-result-attribute-value-count
                         :initform common-lisp:nil)
                        (attribute-names-size-bytes :initarg
                         :attribute-names-size-bytes :type
                         (common-lisp:or long common-lisp:null) :accessor
                         %domain-metadata-result-attribute-names-size-bytes
                         :initform common-lisp:nil)
                        (attribute-name-count :initarg :attribute-name-count
                         :type (common-lisp:or integer common-lisp:null)
                         :accessor %domain-metadata-result-attribute-name-count
                         :initform common-lisp:nil)
                        (item-names-size-bytes :initarg :item-names-size-bytes
                         :type (common-lisp:or long common-lisp:null) :accessor
                         %domain-metadata-result-item-names-size-bytes
                         :initform common-lisp:nil)
                        (item-count :initarg :item-count :type
                         (common-lisp:or integer common-lisp:null) :accessor
                         %domain-metadata-result-item-count :initform
                         common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'domain-metadata-result 'make-domain-metadata-result))
 (common-lisp:defun make-domain-metadata-result
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key timestamp attribute-values-size-bytes
                     attribute-value-count attribute-names-size-bytes
                     attribute-name-count item-names-size-bytes item-count)
   (common-lisp:apply #'common-lisp:make-instance 'domain-metadata-result
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        (
                         (aws-sdk/generator/shape::input
                          domain-metadata-result))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        (
                         (aws-sdk/generator/shape::input
                          domain-metadata-result))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'item-count))
      (common-lisp:list
       (common-lisp:cons "ItemCount"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input
                           'item-names-size-bytes))
      (common-lisp:list
       (common-lisp:cons "ItemNamesSizeBytes"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input
                           'attribute-name-count))
      (common-lisp:list
       (common-lisp:cons "AttributeNameCount"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input
                           'attribute-names-size-bytes))
      (common-lisp:list
       (common-lisp:cons "AttributeNamesSizeBytes"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input
                           'attribute-value-count))
      (common-lisp:list
       (common-lisp:cons "AttributeValueCount"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input
                           'attribute-values-size-bytes))
      (common-lisp:list
       (common-lisp:cons "AttributeValuesSizeBytes"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'timestamp))
      (common-lisp:list
       (common-lisp:cons "Timestamp"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        (
                         (aws-sdk/generator/shape::input
                          domain-metadata-result))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:deftype domain-name-list () '(trivial-types:proper-list string))
 (common-lisp:defun |make-domain-name-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list string))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:define-condition duplicate-item-name
     (sdb-error)
     ((box-usage :initarg :box-usage :initform common-lisp:nil :reader
       duplicate-item-name-box-usage)))
 (common-lisp:export
  (common-lisp:list 'duplicate-item-name 'duplicate-item-name-box-usage)))
(common-lisp:deftype float () 'common-lisp:single-float)
(common-lisp:progn
 (common-lisp:defclass get-attributes-request common-lisp:nil
                       ((consistent-read :initarg :consistent-read :type
                         (common-lisp:or boolean common-lisp:null) :accessor
                         %get-attributes-request-consistent-read :initform
                         common-lisp:nil)
                        (attribute-names :initarg :attribute-names :type
                         (common-lisp:or attribute-name-list common-lisp:null)
                         :accessor %get-attributes-request-attribute-names
                         :initform common-lisp:nil)
                        (item-name :initarg :item-name :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %get-attributes-request-item-name :initform
                         (common-lisp:error ":item-name is required"))
                        (domain-name :initarg :domain-name :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %get-attributes-request-domain-name :initform
                         (common-lisp:error ":domain-name is required"))))
 (common-lisp:export
  (common-lisp:list 'get-attributes-request 'make-get-attributes-request))
 (common-lisp:defun make-get-attributes-request
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key consistent-read attribute-names item-name
                     domain-name)
   (common-lisp:apply #'common-lisp:make-instance 'get-attributes-request
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        (
                         (aws-sdk/generator/shape::input
                          get-attributes-request))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        (
                         (aws-sdk/generator/shape::input
                          get-attributes-request))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'domain-name))
      (common-lisp:list
       (common-lisp:cons "DomainName"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'item-name))
      (common-lisp:list
       (common-lisp:cons "ItemName"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'attribute-names))
      (common-lisp:list
       (common-lisp:cons "AttributeNames"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'consistent-read))
      (common-lisp:list
       (common-lisp:cons "ConsistentRead"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        (
                         (aws-sdk/generator/shape::input
                          get-attributes-request))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:defclass get-attributes-result common-lisp:nil
                       ((attributes :initarg :attributes :type
                         (common-lisp:or attribute-list common-lisp:null)
                         :accessor %get-attributes-result-attributes :initform
                         common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'get-attributes-result 'make-get-attributes-result))
 (common-lisp:defun make-get-attributes-result
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key attributes)
   (common-lisp:apply #'common-lisp:make-instance 'get-attributes-result
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        (
                         (aws-sdk/generator/shape::input
                          get-attributes-result))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        (
                         (aws-sdk/generator/shape::input
                          get-attributes-result))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'attributes))
      (common-lisp:list
       (common-lisp:cons "Attributes"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        (
                         (aws-sdk/generator/shape::input
                          get-attributes-result))
   common-lisp:nil))
(common-lisp:deftype integer () 'common-lisp:integer)
(common-lisp:progn
 (common-lisp:define-condition invalid-next-token
     (sdb-error)
     ((box-usage :initarg :box-usage :initform common-lisp:nil :reader
       invalid-next-token-box-usage)))
 (common-lisp:export
  (common-lisp:list 'invalid-next-token 'invalid-next-token-box-usage)))
(common-lisp:progn
 (common-lisp:define-condition invalid-number-predicates
     (sdb-error)
     ((box-usage :initarg :box-usage :initform common-lisp:nil :reader
       invalid-number-predicates-box-usage)))
 (common-lisp:export
  (common-lisp:list 'invalid-number-predicates
                    'invalid-number-predicates-box-usage)))
(common-lisp:progn
 (common-lisp:define-condition invalid-number-value-tests
     (sdb-error)
     ((box-usage :initarg :box-usage :initform common-lisp:nil :reader
       invalid-number-value-tests-box-usage)))
 (common-lisp:export
  (common-lisp:list 'invalid-number-value-tests
                    'invalid-number-value-tests-box-usage)))
(common-lisp:progn
 (common-lisp:define-condition invalid-parameter-value
     (sdb-error)
     ((box-usage :initarg :box-usage :initform common-lisp:nil :reader
       invalid-parameter-value-box-usage)))
 (common-lisp:export
  (common-lisp:list 'invalid-parameter-value
                    'invalid-parameter-value-box-usage)))
(common-lisp:progn
 (common-lisp:define-condition invalid-query-expression
     (sdb-error)
     ((box-usage :initarg :box-usage :initform common-lisp:nil :reader
       invalid-query-expression-box-usage)))
 (common-lisp:export
  (common-lisp:list 'invalid-query-expression
                    'invalid-query-expression-box-usage)))
(common-lisp:progn
 (common-lisp:defclass item common-lisp:nil
                       ((attributes :initarg :attributes :type
                         (common-lisp:or attribute-list common-lisp:null)
                         :accessor %item-attributes :initform
                         (common-lisp:error ":attributes is required"))
                        (alternate-name-encoding :initarg
                         :alternate-name-encoding :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %item-alternate-name-encoding :initform
                         common-lisp:nil)
                        (name :initarg :name :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %item-name :initform
                         (common-lisp:error ":name is required"))))
 (common-lisp:export (common-lisp:list 'item 'make-item))
 (common-lisp:defun make-item
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key attributes alternate-name-encoding name)
   (common-lisp:apply #'common-lisp:make-instance 'item
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        ((aws-sdk/generator/shape::input item))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        ((aws-sdk/generator/shape::input item))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'name))
      (common-lisp:list
       (common-lisp:cons "Name"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input
                           'alternate-name-encoding))
      (common-lisp:list
       (common-lisp:cons "AlternateNameEncoding"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'attributes))
      (common-lisp:list
       (common-lisp:cons "Attributes"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        ((aws-sdk/generator/shape::input item))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:deftype item-list () '(trivial-types:proper-list item))
 (common-lisp:defun |make-item-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list item))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:defclass list-domains-request common-lisp:nil
                       ((next-token :initarg :next-token :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %list-domains-request-next-token :initform
                         common-lisp:nil)
                        (max-number-of-domains :initarg :max-number-of-domains
                         :type (common-lisp:or integer common-lisp:null)
                         :accessor %list-domains-request-max-number-of-domains
                         :initform common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'list-domains-request 'make-list-domains-request))
 (common-lisp:defun make-list-domains-request
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key next-token max-number-of-domains)
   (common-lisp:apply #'common-lisp:make-instance 'list-domains-request
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        ((aws-sdk/generator/shape::input list-domains-request))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        ((aws-sdk/generator/shape::input list-domains-request))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input
                           'max-number-of-domains))
      (common-lisp:list
       (common-lisp:cons "MaxNumberOfDomains"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'next-token))
      (common-lisp:list
       (common-lisp:cons "NextToken"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        ((aws-sdk/generator/shape::input list-domains-request))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:defclass list-domains-result common-lisp:nil
                       ((next-token :initarg :next-token :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %list-domains-result-next-token :initform
                         common-lisp:nil)
                        (domain-names :initarg :domain-names :type
                         (common-lisp:or domain-name-list common-lisp:null)
                         :accessor %list-domains-result-domain-names :initform
                         common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'list-domains-result 'make-list-domains-result))
 (common-lisp:defun make-list-domains-result
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key next-token domain-names)
   (common-lisp:apply #'common-lisp:make-instance 'list-domains-result
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        ((aws-sdk/generator/shape::input list-domains-result))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        ((aws-sdk/generator/shape::input list-domains-result))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'domain-names))
      (common-lisp:list
       (common-lisp:cons "DomainNames"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'next-token))
      (common-lisp:list
       (common-lisp:cons "NextToken"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        ((aws-sdk/generator/shape::input list-domains-result))
   common-lisp:nil))
(common-lisp:deftype long () 'common-lisp:integer)
(common-lisp:progn
 (common-lisp:define-condition missing-parameter
     (sdb-error)
     ((box-usage :initarg :box-usage :initform common-lisp:nil :reader
       missing-parameter-box-usage)))
 (common-lisp:export
  (common-lisp:list 'missing-parameter 'missing-parameter-box-usage)))
(common-lisp:progn
 (common-lisp:define-condition no-such-domain
     (sdb-error)
     ((box-usage :initarg :box-usage :initform common-lisp:nil :reader
       no-such-domain-box-usage)))
 (common-lisp:export
  (common-lisp:list 'no-such-domain 'no-such-domain-box-usage)))
(common-lisp:progn
 (common-lisp:define-condition number-domain-attributes-exceeded
     (sdb-error)
     ((box-usage :initarg :box-usage :initform common-lisp:nil :reader
       number-domain-attributes-exceeded-box-usage)))
 (common-lisp:export
  (common-lisp:list 'number-domain-attributes-exceeded
                    'number-domain-attributes-exceeded-box-usage)))
(common-lisp:progn
 (common-lisp:define-condition number-domain-bytes-exceeded
     (sdb-error)
     ((box-usage :initarg :box-usage :initform common-lisp:nil :reader
       number-domain-bytes-exceeded-box-usage)))
 (common-lisp:export
  (common-lisp:list 'number-domain-bytes-exceeded
                    'number-domain-bytes-exceeded-box-usage)))
(common-lisp:progn
 (common-lisp:define-condition number-domains-exceeded
     (sdb-error)
     ((box-usage :initarg :box-usage :initform common-lisp:nil :reader
       number-domains-exceeded-box-usage)))
 (common-lisp:export
  (common-lisp:list 'number-domains-exceeded
                    'number-domains-exceeded-box-usage)))
(common-lisp:progn
 (common-lisp:define-condition number-item-attributes-exceeded
     (sdb-error)
     ((box-usage :initarg :box-usage :initform common-lisp:nil :reader
       number-item-attributes-exceeded-box-usage)))
 (common-lisp:export
  (common-lisp:list 'number-item-attributes-exceeded
                    'number-item-attributes-exceeded-box-usage)))
(common-lisp:progn
 (common-lisp:define-condition number-submitted-attributes-exceeded
     (sdb-error)
     ((box-usage :initarg :box-usage :initform common-lisp:nil :reader
       number-submitted-attributes-exceeded-box-usage)))
 (common-lisp:export
  (common-lisp:list 'number-submitted-attributes-exceeded
                    'number-submitted-attributes-exceeded-box-usage)))
(common-lisp:progn
 (common-lisp:define-condition number-submitted-items-exceeded
     (sdb-error)
     ((box-usage :initarg :box-usage :initform common-lisp:nil :reader
       number-submitted-items-exceeded-box-usage)))
 (common-lisp:export
  (common-lisp:list 'number-submitted-items-exceeded
                    'number-submitted-items-exceeded-box-usage)))
(common-lisp:progn
 (common-lisp:defclass put-attributes-request common-lisp:nil
                       ((expected :initarg :expected :type
                         (common-lisp:or update-condition common-lisp:null)
                         :accessor %put-attributes-request-expected :initform
                         common-lisp:nil)
                        (attributes :initarg :attributes :type
                         (common-lisp:or replaceable-attribute-list
                                         common-lisp:null)
                         :accessor %put-attributes-request-attributes :initform
                         (common-lisp:error ":attributes is required"))
                        (item-name :initarg :item-name :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %put-attributes-request-item-name :initform
                         (common-lisp:error ":item-name is required"))
                        (domain-name :initarg :domain-name :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %put-attributes-request-domain-name :initform
                         (common-lisp:error ":domain-name is required"))))
 (common-lisp:export
  (common-lisp:list 'put-attributes-request 'make-put-attributes-request))
 (common-lisp:defun make-put-attributes-request
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key expected attributes item-name
                     domain-name)
   (common-lisp:apply #'common-lisp:make-instance 'put-attributes-request
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        (
                         (aws-sdk/generator/shape::input
                          put-attributes-request))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        (
                         (aws-sdk/generator/shape::input
                          put-attributes-request))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'domain-name))
      (common-lisp:list
       (common-lisp:cons "DomainName"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'item-name))
      (common-lisp:list
       (common-lisp:cons "ItemName"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'attributes))
      (common-lisp:list
       (common-lisp:cons "Attributes"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'expected))
      (common-lisp:list
       (common-lisp:cons "Expected"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        (
                         (aws-sdk/generator/shape::input
                          put-attributes-request))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:defclass replaceable-attribute common-lisp:nil
                       ((replace :initarg :replace :type
                         (common-lisp:or boolean common-lisp:null) :accessor
                         %replaceable-attribute-replace :initform
                         common-lisp:nil)
                        (value :initarg :value :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %replaceable-attribute-value :initform
                         (common-lisp:error ":value is required"))
                        (name :initarg :name :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %replaceable-attribute-name :initform
                         (common-lisp:error ":name is required"))))
 (common-lisp:export
  (common-lisp:list 'replaceable-attribute 'make-replaceable-attribute))
 (common-lisp:defun make-replaceable-attribute
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key replace value name)
   (common-lisp:apply #'common-lisp:make-instance 'replaceable-attribute
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        (
                         (aws-sdk/generator/shape::input
                          replaceable-attribute))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        (
                         (aws-sdk/generator/shape::input
                          replaceable-attribute))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'name))
      (common-lisp:list
       (common-lisp:cons "Name"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'value))
      (common-lisp:list
       (common-lisp:cons "Value"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'replace))
      (common-lisp:list
       (common-lisp:cons "Replace"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        (
                         (aws-sdk/generator/shape::input
                          replaceable-attribute))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:deftype replaceable-attribute-list ()
   '(trivial-types:proper-list replaceable-attribute))
 (common-lisp:defun |make-replaceable-attribute-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list replaceable-attribute))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:defclass replaceable-item common-lisp:nil
                       ((attributes :initarg :attributes :type
                         (common-lisp:or replaceable-attribute-list
                                         common-lisp:null)
                         :accessor %replaceable-item-attributes :initform
                         (common-lisp:error ":attributes is required"))
                        (name :initarg :name :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %replaceable-item-name :initform
                         (common-lisp:error ":name is required"))))
 (common-lisp:export
  (common-lisp:list 'replaceable-item 'make-replaceable-item))
 (common-lisp:defun make-replaceable-item
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key attributes name)
   (common-lisp:apply #'common-lisp:make-instance 'replaceable-item
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        ((aws-sdk/generator/shape::input replaceable-item))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        ((aws-sdk/generator/shape::input replaceable-item))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'name))
      (common-lisp:list
       (common-lisp:cons "Name"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'attributes))
      (common-lisp:list
       (common-lisp:cons "Attributes"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        ((aws-sdk/generator/shape::input replaceable-item))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:deftype replaceable-item-list ()
   '(trivial-types:proper-list replaceable-item))
 (common-lisp:defun |make-replaceable-item-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list replaceable-item))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:define-condition request-timeout
     (sdb-error)
     ((box-usage :initarg :box-usage :initform common-lisp:nil :reader
       request-timeout-box-usage)))
 (common-lisp:export
  (common-lisp:list 'request-timeout 'request-timeout-box-usage)))
(common-lisp:progn
 (common-lisp:defclass select-request common-lisp:nil
                       ((consistent-read :initarg :consistent-read :type
                         (common-lisp:or boolean common-lisp:null) :accessor
                         %select-request-consistent-read :initform
                         common-lisp:nil)
                        (next-token :initarg :next-token :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %select-request-next-token :initform common-lisp:nil)
                        (select-expression :initarg :select-expression :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %select-request-select-expression :initform
                         (common-lisp:error
                          ":select-expression is required"))))
 (common-lisp:export (common-lisp:list 'select-request 'make-select-request))
 (common-lisp:defun make-select-request
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key consistent-read next-token
                     select-expression)
   (common-lisp:apply #'common-lisp:make-instance 'select-request
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        ((aws-sdk/generator/shape::input select-request))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        ((aws-sdk/generator/shape::input select-request))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'select-expression))
      (common-lisp:list
       (common-lisp:cons "SelectExpression"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'next-token))
      (common-lisp:list
       (common-lisp:cons "NextToken"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'consistent-read))
      (common-lisp:list
       (common-lisp:cons "ConsistentRead"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        ((aws-sdk/generator/shape::input select-request))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:defclass select-result common-lisp:nil
                       ((next-token :initarg :next-token :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %select-result-next-token :initform common-lisp:nil)
                        (items :initarg :items :type
                         (common-lisp:or item-list common-lisp:null) :accessor
                         %select-result-items :initform common-lisp:nil)))
 (common-lisp:export (common-lisp:list 'select-result 'make-select-result))
 (common-lisp:defun make-select-result
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key next-token items)
   (common-lisp:apply #'common-lisp:make-instance 'select-result
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        ((aws-sdk/generator/shape::input select-result))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        ((aws-sdk/generator/shape::input select-result))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'items))
      (common-lisp:list
       (common-lisp:cons "Items"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'next-token))
      (common-lisp:list
       (common-lisp:cons "NextToken"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        ((aws-sdk/generator/shape::input select-result))
   common-lisp:nil))
(common-lisp:deftype string () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:define-condition too-many-requested-attributes
     (sdb-error)
     ((box-usage :initarg :box-usage :initform common-lisp:nil :reader
       too-many-requested-attributes-box-usage)))
 (common-lisp:export
  (common-lisp:list 'too-many-requested-attributes
                    'too-many-requested-attributes-box-usage)))
(common-lisp:progn
 (common-lisp:defclass update-condition common-lisp:nil
                       ((exists :initarg :exists :type
                         (common-lisp:or boolean common-lisp:null) :accessor
                         %update-condition-exists :initform common-lisp:nil)
                        (value :initarg :value :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %update-condition-value :initform common-lisp:nil)
                        (name :initarg :name :type
                         (common-lisp:or string common-lisp:null) :accessor
                         %update-condition-name :initform common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'update-condition 'make-update-condition))
 (common-lisp:defun make-update-condition
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key exists value name)
   (common-lisp:apply #'common-lisp:make-instance 'update-condition
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        ((aws-sdk/generator/shape::input update-condition))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        ((aws-sdk/generator/shape::input update-condition))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'name))
      (common-lisp:list
       (common-lisp:cons "Name"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'value))
      (common-lisp:list
       (common-lisp:cons "Value"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'exists))
      (common-lisp:list
       (common-lisp:cons "Exists"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        ((aws-sdk/generator/shape::input update-condition))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:defun batch-delete-attributes
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key domain-name items)
   (common-lisp:declare (common-lisp:ignorable domain-name items))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-batch-delete-attributes-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (aws-sdk/generator/shape:make-request-with-input 'sdb-request
                                                        aws-sdk/generator/operation::input
                                                        "POST" :query "/"
                                                        "BatchDeleteAttributes"
                                                        "2009-04-15"))
      common-lisp:nil common-lisp:nil *error-map*)))
 (common-lisp:export 'batch-delete-attributes))
(common-lisp:progn
 (common-lisp:defun batch-put-attributes
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key domain-name items)
   (common-lisp:declare (common-lisp:ignorable domain-name items))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-batch-put-attributes-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (aws-sdk/generator/shape:make-request-with-input 'sdb-request
                                                        aws-sdk/generator/operation::input
                                                        "POST" :query "/"
                                                        "BatchPutAttributes"
                                                        "2009-04-15"))
      common-lisp:nil common-lisp:nil *error-map*)))
 (common-lisp:export 'batch-put-attributes))
(common-lisp:progn
 (common-lisp:defun create-domain
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key domain-name)
   (common-lisp:declare (common-lisp:ignorable domain-name))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-create-domain-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (aws-sdk/generator/shape:make-request-with-input 'sdb-request
                                                        aws-sdk/generator/operation::input
                                                        "POST" :query "/"
                                                        "CreateDomain"
                                                        "2009-04-15"))
      common-lisp:nil common-lisp:nil *error-map*)))
 (common-lisp:export 'create-domain))
(common-lisp:progn
 (common-lisp:defun delete-attributes
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key domain-name item-name attributes
                     expected)
   (common-lisp:declare
    (common-lisp:ignorable domain-name item-name attributes expected))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-delete-attributes-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (aws-sdk/generator/shape:make-request-with-input 'sdb-request
                                                        aws-sdk/generator/operation::input
                                                        "POST" :query "/"
                                                        "DeleteAttributes"
                                                        "2009-04-15"))
      common-lisp:nil common-lisp:nil *error-map*)))
 (common-lisp:export 'delete-attributes))
(common-lisp:progn
 (common-lisp:defun delete-domain
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key domain-name)
   (common-lisp:declare (common-lisp:ignorable domain-name))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-delete-domain-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (aws-sdk/generator/shape:make-request-with-input 'sdb-request
                                                        aws-sdk/generator/operation::input
                                                        "POST" :query "/"
                                                        "DeleteDomain"
                                                        "2009-04-15"))
      common-lisp:nil common-lisp:nil *error-map*)))
 (common-lisp:export 'delete-domain))
(common-lisp:progn
 (common-lisp:defun domain-metadata
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key domain-name)
   (common-lisp:declare (common-lisp:ignorable domain-name))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-domain-metadata-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (aws-sdk/generator/shape:make-request-with-input 'sdb-request
                                                        aws-sdk/generator/operation::input
                                                        "POST" :query "/"
                                                        "DomainMetadata"
                                                        "2009-04-15"))
      common-lisp:nil "DomainMetadataResult" *error-map*)))
 (common-lisp:export 'domain-metadata))
(common-lisp:progn
 (common-lisp:defun get-attributes
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key domain-name item-name attribute-names
                     consistent-read)
   (common-lisp:declare
    (common-lisp:ignorable domain-name item-name attribute-names
     consistent-read))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-get-attributes-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (aws-sdk/generator/shape:make-request-with-input 'sdb-request
                                                        aws-sdk/generator/operation::input
                                                        "POST" :query "/"
                                                        "GetAttributes"
                                                        "2009-04-15"))
      common-lisp:nil "GetAttributesResult" *error-map*)))
 (common-lisp:export 'get-attributes))
(common-lisp:progn
 (common-lisp:defun list-domains
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key max-number-of-domains next-token)
   (common-lisp:declare
    (common-lisp:ignorable max-number-of-domains next-token))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-list-domains-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (aws-sdk/generator/shape:make-request-with-input 'sdb-request
                                                        aws-sdk/generator/operation::input
                                                        "POST" :query "/"
                                                        "ListDomains"
                                                        "2009-04-15"))
      common-lisp:nil "ListDomainsResult" *error-map*)))
 (common-lisp:export 'list-domains))
(common-lisp:progn
 (common-lisp:defun put-attributes
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key domain-name item-name attributes
                     expected)
   (common-lisp:declare
    (common-lisp:ignorable domain-name item-name attributes expected))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-put-attributes-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (aws-sdk/generator/shape:make-request-with-input 'sdb-request
                                                        aws-sdk/generator/operation::input
                                                        "POST" :query "/"
                                                        "PutAttributes"
                                                        "2009-04-15"))
      common-lisp:nil common-lisp:nil *error-map*)))
 (common-lisp:export 'put-attributes))
(common-lisp:progn
 (common-lisp:defun select
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key select-expression next-token
                     consistent-read)
   (common-lisp:declare
    (common-lisp:ignorable select-expression next-token consistent-read))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-select-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (aws-sdk/generator/shape:make-request-with-input 'sdb-request
                                                        aws-sdk/generator/operation::input
                                                        "POST" :query "/"
                                                        "Select" "2009-04-15"))
      common-lisp:nil "SelectResult" *error-map*)))
 (common-lisp:export 'select))
