;; DO NOT EDIT: File is generated by AWS-SDK/GENERATOR.

(common-lisp:defpackage #:aws-sdk/services/sso-oidc/api
  (:use)
  (:nicknames #:aws/sso-oidc)
  (:import-from #:aws-sdk/generator/shape)
  (:import-from #:aws-sdk/generator/operation)
  (:import-from #:aws-sdk/api)
  (:import-from #:aws-sdk/request)
  (:import-from #:aws-sdk/error))
(common-lisp:in-package #:aws-sdk/services/sso-oidc/api)
(common-lisp:progn
 (common-lisp:defclass sso-oidc-request (aws-sdk/request:request)
                       common-lisp:nil
                       (:default-initargs :service "sso-oidc" :protocol
                        :rest-json))
 (common-lisp:export 'sso-oidc-request))
(common-lisp:progn
 (common-lisp:define-condition sso-oidc-error
     (aws-sdk/error:aws-error)
     common-lisp:nil)
 (common-lisp:export 'sso-oidc-error))
(common-lisp:defvar *error-map*
  '(("AccessDeniedException" . access-denied-exception)
    ("AuthorizationPendingException" . authorization-pending-exception)
    ("ExpiredTokenException" . expired-token-exception)
    ("InternalServerException" . internal-server-exception)
    ("InvalidClientException" . invalid-client-exception)
    ("InvalidClientMetadataException" . invalid-client-metadata-exception)
    ("InvalidGrantException" . invalid-grant-exception)
    ("InvalidRequestException" . invalid-request-exception)
    ("InvalidScopeException" . invalid-scope-exception)
    ("SlowDownException" . slow-down-exception)
    ("UnauthorizedClientException" . unauthorized-client-exception)
    ("UnsupportedGrantTypeException" . unsupported-grant-type-exception)))
(common-lisp:progn
 (common-lisp:define-condition access-denied-exception
     (sso-oidc-error)
     ((error :initarg :|error| :initform common-lisp:nil :reader
       access-denied-exception-error)
      (error-description :initarg :|error_description| :initform
       common-lisp:nil :reader access-denied-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'access-denied-exception 'access-denied-exception-error
                    'access-denied-exception-error-description)))
(common-lisp:deftype access-token () 'common-lisp:string)
(common-lisp:deftype auth-code () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:define-condition authorization-pending-exception
     (sso-oidc-error)
     ((error :initarg :|error| :initform common-lisp:nil :reader
       authorization-pending-exception-error)
      (error-description :initarg :|error_description| :initform
       common-lisp:nil :reader
       authorization-pending-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'authorization-pending-exception
                    'authorization-pending-exception-error
                    'authorization-pending-exception-error-description)))
(common-lisp:deftype client-id () 'common-lisp:string)
(common-lisp:deftype client-name () 'common-lisp:string)
(common-lisp:deftype client-secret () 'common-lisp:string)
(common-lisp:deftype client-type () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defclass create-token-request common-lisp:nil
                       ((redirect-uri :initarg :|redirectUri| :type
                         (common-lisp:or uri common-lisp:null) :accessor
                         %create-token-request-redirect-uri :initform
                         common-lisp:nil)
                        (scope :initarg :|scope| :type
                         (common-lisp:or scopes common-lisp:null) :accessor
                         %create-token-request-scope :initform common-lisp:nil)
                        (refresh-token :initarg :|refreshToken| :type
                         (common-lisp:or refresh-token common-lisp:null)
                         :accessor %create-token-request-refresh-token
                         :initform common-lisp:nil)
                        (code :initarg :|code| :type
                         (common-lisp:or auth-code common-lisp:null) :accessor
                         %create-token-request-code :initform common-lisp:nil)
                        (device-code :initarg :|deviceCode| :type
                         (common-lisp:or device-code common-lisp:null)
                         :accessor %create-token-request-device-code :initform
                         common-lisp:nil)
                        (grant-type :initarg :|grantType| :type
                         (common-lisp:or grant-type common-lisp:null) :accessor
                         %create-token-request-grant-type :initform
                         (common-lisp:error ":granttype is required"))
                        (client-secret :initarg :|clientSecret| :type
                         (common-lisp:or client-secret common-lisp:null)
                         :accessor %create-token-request-client-secret
                         :initform
                         (common-lisp:error ":clientsecret is required"))
                        (client-id :initarg :|clientId| :type
                         (common-lisp:or client-id common-lisp:null) :accessor
                         %create-token-request-client-id :initform
                         (common-lisp:error ":clientid is required"))))
 (common-lisp:export
  (common-lisp:list 'create-token-request 'make-create-token-request))
 (common-lisp:defun make-create-token-request
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key redirect-uri scope refresh-token code
                     device-code grant-type client-secret client-id)
   (common-lisp:apply #'common-lisp:make-instance 'create-token-request
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        ((aws-sdk/generator/shape::input create-token-request))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        ((aws-sdk/generator/shape::input create-token-request))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'client-id))
      (common-lisp:list
       (common-lisp:cons "clientId"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'client-secret))
      (common-lisp:list
       (common-lisp:cons "clientSecret"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'grant-type))
      (common-lisp:list
       (common-lisp:cons "grantType"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'device-code))
      (common-lisp:list
       (common-lisp:cons "deviceCode"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'code))
      (common-lisp:list
       (common-lisp:cons "code"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'refresh-token))
      (common-lisp:list
       (common-lisp:cons "refreshToken"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'scope))
      (common-lisp:list
       (common-lisp:cons "scope"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'redirect-uri))
      (common-lisp:list
       (common-lisp:cons "redirectUri"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        ((aws-sdk/generator/shape::input create-token-request))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:defclass create-token-response common-lisp:nil
                       ((id-token :initarg :|idToken| :type
                         (common-lisp:or id-token common-lisp:null) :accessor
                         %create-token-response-id-token :initform
                         common-lisp:nil)
                        (refresh-token :initarg :|refreshToken| :type
                         (common-lisp:or refresh-token common-lisp:null)
                         :accessor %create-token-response-refresh-token
                         :initform common-lisp:nil)
                        (expires-in :initarg :|expiresIn| :type
                         (common-lisp:or expiration-in-seconds
                                         common-lisp:null)
                         :accessor %create-token-response-expires-in :initform
                         common-lisp:nil)
                        (token-type :initarg :|tokenType| :type
                         (common-lisp:or token-type common-lisp:null) :accessor
                         %create-token-response-token-type :initform
                         common-lisp:nil)
                        (access-token :initarg :|accessToken| :type
                         (common-lisp:or access-token common-lisp:null)
                         :accessor %create-token-response-access-token
                         :initform common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'create-token-response 'make-create-token-response))
 (common-lisp:defun make-create-token-response
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key id-token refresh-token expires-in
                     token-type access-token)
   (common-lisp:apply #'common-lisp:make-instance 'create-token-response
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        (
                         (aws-sdk/generator/shape::input
                          create-token-response))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        (
                         (aws-sdk/generator/shape::input
                          create-token-response))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'access-token))
      (common-lisp:list
       (common-lisp:cons "accessToken"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'token-type))
      (common-lisp:list
       (common-lisp:cons "tokenType"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'expires-in))
      (common-lisp:list
       (common-lisp:cons "expiresIn"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'refresh-token))
      (common-lisp:list
       (common-lisp:cons "refreshToken"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'id-token))
      (common-lisp:list
       (common-lisp:cons "idToken"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        (
                         (aws-sdk/generator/shape::input
                          create-token-response))
   common-lisp:nil))
(common-lisp:deftype device-code () 'common-lisp:string)
(common-lisp:deftype error () 'common-lisp:string)
(common-lisp:deftype error-description () 'common-lisp:string)
(common-lisp:deftype expiration-in-seconds () 'common-lisp:integer)
(common-lisp:progn
 (common-lisp:define-condition expired-token-exception
     (sso-oidc-error)
     ((error :initarg :|error| :initform common-lisp:nil :reader
       expired-token-exception-error)
      (error-description :initarg :|error_description| :initform
       common-lisp:nil :reader expired-token-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'expired-token-exception 'expired-token-exception-error
                    'expired-token-exception-error-description)))
(common-lisp:deftype grant-type () 'common-lisp:string)
(common-lisp:deftype id-token () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:define-condition internal-server-exception
     (sso-oidc-error)
     ((error :initarg :|error| :initform common-lisp:nil :reader
       internal-server-exception-error)
      (error-description :initarg :|error_description| :initform
       common-lisp:nil :reader internal-server-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'internal-server-exception 'internal-server-exception-error
                    'internal-server-exception-error-description)))
(common-lisp:deftype interval-in-seconds () 'common-lisp:integer)
(common-lisp:progn
 (common-lisp:define-condition invalid-client-exception
     (sso-oidc-error)
     ((error :initarg :|error| :initform common-lisp:nil :reader
       invalid-client-exception-error)
      (error-description :initarg :|error_description| :initform
       common-lisp:nil :reader invalid-client-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'invalid-client-exception 'invalid-client-exception-error
                    'invalid-client-exception-error-description)))
(common-lisp:progn
 (common-lisp:define-condition invalid-client-metadata-exception
     (sso-oidc-error)
     ((error :initarg :|error| :initform common-lisp:nil :reader
       invalid-client-metadata-exception-error)
      (error-description :initarg :|error_description| :initform
       common-lisp:nil :reader
       invalid-client-metadata-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'invalid-client-metadata-exception
                    'invalid-client-metadata-exception-error
                    'invalid-client-metadata-exception-error-description)))
(common-lisp:progn
 (common-lisp:define-condition invalid-grant-exception
     (sso-oidc-error)
     ((error :initarg :|error| :initform common-lisp:nil :reader
       invalid-grant-exception-error)
      (error-description :initarg :|error_description| :initform
       common-lisp:nil :reader invalid-grant-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'invalid-grant-exception 'invalid-grant-exception-error
                    'invalid-grant-exception-error-description)))
(common-lisp:progn
 (common-lisp:define-condition invalid-request-exception
     (sso-oidc-error)
     ((error :initarg :|error| :initform common-lisp:nil :reader
       invalid-request-exception-error)
      (error-description :initarg :|error_description| :initform
       common-lisp:nil :reader invalid-request-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'invalid-request-exception 'invalid-request-exception-error
                    'invalid-request-exception-error-description)))
(common-lisp:progn
 (common-lisp:define-condition invalid-scope-exception
     (sso-oidc-error)
     ((error :initarg :|error| :initform common-lisp:nil :reader
       invalid-scope-exception-error)
      (error-description :initarg :|error_description| :initform
       common-lisp:nil :reader invalid-scope-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'invalid-scope-exception 'invalid-scope-exception-error
                    'invalid-scope-exception-error-description)))
(common-lisp:deftype long-time-stamp-type () 'common-lisp:integer)
(common-lisp:deftype refresh-token () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defclass register-client-request common-lisp:nil
                       ((scopes :initarg :|scopes| :type
                         (common-lisp:or scopes common-lisp:null) :accessor
                         %register-client-request-scopes :initform
                         common-lisp:nil)
                        (client-type :initarg :|clientType| :type
                         (common-lisp:or client-type common-lisp:null)
                         :accessor %register-client-request-client-type
                         :initform
                         (common-lisp:error ":clienttype is required"))
                        (client-name :initarg :|clientName| :type
                         (common-lisp:or client-name common-lisp:null)
                         :accessor %register-client-request-client-name
                         :initform
                         (common-lisp:error ":clientname is required"))))
 (common-lisp:export
  (common-lisp:list 'register-client-request 'make-register-client-request))
 (common-lisp:defun make-register-client-request
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key scopes client-type client-name)
   (common-lisp:apply #'common-lisp:make-instance 'register-client-request
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        (
                         (aws-sdk/generator/shape::input
                          register-client-request))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        (
                         (aws-sdk/generator/shape::input
                          register-client-request))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'client-name))
      (common-lisp:list
       (common-lisp:cons "clientName"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'client-type))
      (common-lisp:list
       (common-lisp:cons "clientType"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'scopes))
      (common-lisp:list
       (common-lisp:cons "scopes"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        (
                         (aws-sdk/generator/shape::input
                          register-client-request))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:defclass register-client-response common-lisp:nil
                       ((token-endpoint :initarg :|tokenEndpoint| :type
                         (common-lisp:or uri common-lisp:null) :accessor
                         %register-client-response-token-endpoint :initform
                         common-lisp:nil)
                        (authorization-endpoint :initarg
                         :|authorizationEndpoint| :type
                         (common-lisp:or uri common-lisp:null) :accessor
                         %register-client-response-authorization-endpoint
                         :initform common-lisp:nil)
                        (client-secret-expires-at :initarg
                         :|clientSecretExpiresAt| :type
                         (common-lisp:or long-time-stamp-type common-lisp:null)
                         :accessor
                         %register-client-response-client-secret-expires-at
                         :initform common-lisp:nil)
                        (client-id-issued-at :initarg :|clientIdIssuedAt| :type
                         (common-lisp:or long-time-stamp-type common-lisp:null)
                         :accessor
                         %register-client-response-client-id-issued-at
                         :initform common-lisp:nil)
                        (client-secret :initarg :|clientSecret| :type
                         (common-lisp:or client-secret common-lisp:null)
                         :accessor %register-client-response-client-secret
                         :initform common-lisp:nil)
                        (client-id :initarg :|clientId| :type
                         (common-lisp:or client-id common-lisp:null) :accessor
                         %register-client-response-client-id :initform
                         common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'register-client-response 'make-register-client-response))
 (common-lisp:defun make-register-client-response
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key token-endpoint authorization-endpoint
                     client-secret-expires-at client-id-issued-at client-secret
                     client-id)
   (common-lisp:apply #'common-lisp:make-instance 'register-client-response
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        (
                         (aws-sdk/generator/shape::input
                          register-client-response))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        (
                         (aws-sdk/generator/shape::input
                          register-client-response))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'client-id))
      (common-lisp:list
       (common-lisp:cons "clientId"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'client-secret))
      (common-lisp:list
       (common-lisp:cons "clientSecret"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'client-id-issued-at))
      (common-lisp:list
       (common-lisp:cons "clientIdIssuedAt"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input
                           'client-secret-expires-at))
      (common-lisp:list
       (common-lisp:cons "clientSecretExpiresAt"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input
                           'authorization-endpoint))
      (common-lisp:list
       (common-lisp:cons "authorizationEndpoint"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'token-endpoint))
      (common-lisp:list
       (common-lisp:cons "tokenEndpoint"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        (
                         (aws-sdk/generator/shape::input
                          register-client-response))
   common-lisp:nil))
(common-lisp:deftype scope () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype scopes () '(trivial-types:proper-list scope))
 (common-lisp:defun |make-scopes|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list scope))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:define-condition slow-down-exception
     (sso-oidc-error)
     ((error :initarg :|error| :initform common-lisp:nil :reader
       slow-down-exception-error)
      (error-description :initarg :|error_description| :initform
       common-lisp:nil :reader slow-down-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'slow-down-exception 'slow-down-exception-error
                    'slow-down-exception-error-description)))
(common-lisp:progn
 (common-lisp:defclass start-device-authorization-request common-lisp:nil
                       ((start-url :initarg :|startUrl| :type
                         (common-lisp:or uri common-lisp:null) :accessor
                         %start-device-authorization-request-start-url
                         :initform (common-lisp:error ":starturl is required"))
                        (client-secret :initarg :|clientSecret| :type
                         (common-lisp:or client-secret common-lisp:null)
                         :accessor
                         %start-device-authorization-request-client-secret
                         :initform
                         (common-lisp:error ":clientsecret is required"))
                        (client-id :initarg :|clientId| :type
                         (common-lisp:or client-id common-lisp:null) :accessor
                         %start-device-authorization-request-client-id
                         :initform
                         (common-lisp:error ":clientid is required"))))
 (common-lisp:export
  (common-lisp:list 'start-device-authorization-request
                    'make-start-device-authorization-request))
 (common-lisp:defun make-start-device-authorization-request
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key start-url client-secret client-id)
   (common-lisp:apply #'common-lisp:make-instance
                      'start-device-authorization-request
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        (
                         (aws-sdk/generator/shape::input
                          start-device-authorization-request))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        (
                         (aws-sdk/generator/shape::input
                          start-device-authorization-request))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'client-id))
      (common-lisp:list
       (common-lisp:cons "clientId"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'client-secret))
      (common-lisp:list
       (common-lisp:cons "clientSecret"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'start-url))
      (common-lisp:list
       (common-lisp:cons "startUrl"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        (
                         (aws-sdk/generator/shape::input
                          start-device-authorization-request))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:defclass start-device-authorization-response common-lisp:nil
                       ((interval :initarg :|interval| :type
                         (common-lisp:or interval-in-seconds common-lisp:null)
                         :accessor
                         %start-device-authorization-response-interval
                         :initform common-lisp:nil)
                        (expires-in :initarg :|expiresIn| :type
                         (common-lisp:or expiration-in-seconds
                                         common-lisp:null)
                         :accessor
                         %start-device-authorization-response-expires-in
                         :initform common-lisp:nil)
                        (verification-uri-complete :initarg
                         :|verificationUriComplete| :type
                         (common-lisp:or uri common-lisp:null) :accessor
                         %start-device-authorization-response-verification-uri-complete
                         :initform common-lisp:nil)
                        (verification-uri :initarg :|verificationUri| :type
                         (common-lisp:or uri common-lisp:null) :accessor
                         %start-device-authorization-response-verification-uri
                         :initform common-lisp:nil)
                        (user-code :initarg :|userCode| :type
                         (common-lisp:or user-code common-lisp:null) :accessor
                         %start-device-authorization-response-user-code
                         :initform common-lisp:nil)
                        (device-code :initarg :|deviceCode| :type
                         (common-lisp:or device-code common-lisp:null)
                         :accessor
                         %start-device-authorization-response-device-code
                         :initform common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'start-device-authorization-response
                    'make-start-device-authorization-response))
 (common-lisp:defun make-start-device-authorization-response
                    (
                     common-lisp:&rest aws-sdk/generator/shape::args
                     common-lisp:&key interval expires-in
                     verification-uri-complete verification-uri user-code
                     device-code)
   (common-lisp:apply #'common-lisp:make-instance
                      'start-device-authorization-response
                      aws-sdk/generator/shape::args))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        (
                         (aws-sdk/generator/shape::input
                          start-device-authorization-response))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        (
                         (aws-sdk/generator/shape::input
                          start-device-authorization-response))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'device-code))
      (common-lisp:list
       (common-lisp:cons "deviceCode"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'user-code))
      (common-lisp:list
       (common-lisp:cons "userCode"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'verification-uri))
      (common-lisp:list
       (common-lisp:cons "verificationUri"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input
                           'verification-uri-complete))
      (common-lisp:list
       (common-lisp:cons "verificationUriComplete"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'expires-in))
      (common-lisp:list
       (common-lisp:cons "expiresIn"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'interval))
      (common-lisp:list
       (common-lisp:cons "interval"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        (
                         (aws-sdk/generator/shape::input
                          start-device-authorization-response))
   common-lisp:nil))
(common-lisp:deftype token-type () 'common-lisp:string)
(common-lisp:deftype uri () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:define-condition unauthorized-client-exception
     (sso-oidc-error)
     ((error :initarg :|error| :initform common-lisp:nil :reader
       unauthorized-client-exception-error)
      (error-description :initarg :|error_description| :initform
       common-lisp:nil :reader
       unauthorized-client-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'unauthorized-client-exception
                    'unauthorized-client-exception-error
                    'unauthorized-client-exception-error-description)))
(common-lisp:progn
 (common-lisp:define-condition unsupported-grant-type-exception
     (sso-oidc-error)
     ((error :initarg :|error| :initform common-lisp:nil :reader
       unsupported-grant-type-exception-error)
      (error-description :initarg :|error_description| :initform
       common-lisp:nil :reader
       unsupported-grant-type-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'unsupported-grant-type-exception
                    'unsupported-grant-type-exception-error
                    'unsupported-grant-type-exception-error-description)))
(common-lisp:deftype user-code () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defun create-token
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key client-id client-secret grant-type
                     device-code code refresh-token scope redirect-uri)
   (common-lisp:declare
    (common-lisp:ignorable client-id client-secret grant-type device-code code
     refresh-token scope redirect-uri))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-create-token-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (aws-sdk/generator/shape:make-request-with-input 'sso-oidc-request
                                                        aws-sdk/generator/operation::input
                                                        "POST" :rest-json
                                                        "/token" "CreateToken"
                                                        "2019-06-10"))
      common-lisp:nil common-lisp:nil *error-map*)))
 (common-lisp:export 'create-token))
(common-lisp:progn
 (common-lisp:defun register-client
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key client-name client-type scopes)
   (common-lisp:declare (common-lisp:ignorable client-name client-type scopes))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-register-client-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (aws-sdk/generator/shape:make-request-with-input 'sso-oidc-request
                                                        aws-sdk/generator/operation::input
                                                        "POST" :rest-json
                                                        "/client/register"
                                                        "RegisterClient"
                                                        "2019-06-10"))
      common-lisp:nil common-lisp:nil *error-map*)))
 (common-lisp:export 'register-client))
(common-lisp:progn
 (common-lisp:defun start-device-authorization
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key client-id client-secret start-url)
   (common-lisp:declare
    (common-lisp:ignorable client-id client-secret start-url))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply
                       'make-start-device-authorization-request
                       aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (aws-sdk/generator/shape:make-request-with-input 'sso-oidc-request
                                                        aws-sdk/generator/operation::input
                                                        "POST" :rest-json
                                                        "/device_authorization"
                                                        "StartDeviceAuthorization"
                                                        "2019-06-10"))
      common-lisp:nil common-lisp:nil *error-map*)))
 (common-lisp:export 'start-device-authorization))
